# code: language=ansible
---
- name: "Join worker nodes to the cluster with registered join token (if the controller was bootstrapped by the same playbook)"
  ansible.builtin.command: "sudo {{ hostvars[groups['kube_ctrl'][0]]['worker_join_token']['stdout'] }}"
  when: hostvars[groups['kube_ctrl'][0]]['worker_join_token'] is defined

- name: "Join worker nodes with the join token from user-defined variable"
  ansible.builtin.command: "sudo {{ k8s_add_worker_node_join_token }}"
  when: hostvars[groups['kube_ctrl'][0]]['worker_join_token'] is undefined

- name: "Wait for all k8s nodes to be ready"
  become: false
  delegate_to: '{{ groups.kube_ctrl[0] }}'
  ansible.builtin.command: kubectl --kubeconfig={{ k8s_add_worker_node_kube_config }} wait --for=condition=Ready nodes --all --timeout=600s
  register: nodes_ready

- name: "Display nodes readiness"
  ansible.builtin.debug:
    msg: "{{ nodes_ready.stdout_lines }}"

- name: "Join final message"
  ansible.builtin.debug:
    msg: "All nodes are Ready. Now check pods with 'kubectl get pods --all-namespaces' and nodes with 'kubectl get nodes'"
