# code: language=ansible
---
- name: "Prepare nodes for bootstraping a k8s cluster"
  hosts: all
  vars:
    k8s_prep_node_k8s_packages:
      - name: "containerd.io"
        version: "1.6.4-1"
      - name: "kubelet"
        version: "1.22.0-00"
      - name: "kubeadm"
        version: "1.22.0-00"
      - name: "kubectl"
        version: "1.22.0-00"
  force_handlers: true
  roles:
    - k8s_prepare_node

- name: "Bootstrap k8s cluster and configure calico"
  hosts: kube_ctrl[0]
  roles:
    - k8s_bootstrap_single_controller
    - k8s_addon_calico

- name: "Add worker nodes"
  hosts: kube_workers
  roles:
    - k8s_add_worker_node
