# code: language=ansible
- name: Asdasd
  hosts: s1-pg01.nokogerra.lab
  vars:
    k8s_prep_node_repos:
      - name: docker
        key_url: https://download.docker.com/linux/ubuntu/gpg
        key_file: docker.gpg
        repo_string: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        repo_file: docker
      - name: kubernetes
        key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        key_file: kubernetes.gpg
        repo_string: "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        repo_file: kubernetes
  tasks:
    - name: "Add k8s and docker repos keys"
      ansible.builtin.apt_key:
        url: "{{ item.key_url }}"
        keyring: "/etc/apt/keyrings/{{ item.key_file }}"
      loop: "{{ k8s_prep_node_repos }}"
    - name: "Add k8s and docker repositories"
      ansible.builtin.apt_repository:
        repo: "{{ item.repo_string }}"
        filename: "{{ item.repo_file }}"
        state: present
      loop: "{{ k8s_prep_node_repos }}"
