# code: language=ansible
---
- name: "Launch tigera-operator"
  become: false
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_addon_calico_kube_config }}"
    state: present
    src: "https://raw.githubusercontent.com/projectcalico/calico/{{ k8s_addon_calico_version }}/manifests/tigera-operator.yaml"

- name: "Verify tigera-operator pod(s) is(are) Ready"
  become: false
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_addon_calico_kube_config }}"
    kind: Pod
    wait: true
    label_selectors:
      - k8s-app=tigera-operator
    wait_timeout: 300
    wait_sleep: 5
    wait_condition:
      type: Ready
      status: "True"

- name: "Make calico configuration manifest"
  become: false
  ansible.builtin.template:
    src: calico.yml.j2
    dest: "/home/{{ ansible_user }}/calico.yml"

- name: "Apply calico configuration manifest"
  become: false
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_addon_calico_kube_config }}"
    state: present
    src: "/home/{{ ansible_user }}/calico.yml"

- name: "Wait for all k8s nodes to be ready"
  ansible.builtin.command: kubectl --kubeconfig={{ k8s_addon_calico_kube_config }} wait --for=condition=Ready nodes --all --timeout=600s
  register: nodes_ready

- name: "Display nodes readiness"
  ansible.builtin.debug:
    msg: "{{ nodes_ready.stdout_lines }}"

- name: "Verify calico components (csi-node-driver, typha, node, kube-controllers, apiserver) to be ready"
  become: false
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_addon_calico_kube_config }}"
    kind: Pod
    wait: true
    label_selectors: "{{ item }}"
    wait_timeout: 300
    wait_sleep: 3
    wait_condition:
      type: Ready
      status: "True"
  loop:
    - k8s-app=csi-node-driver
    - k8s-app=calico-typha
    - k8s-app=calico-node
    - k8s-app=calico-kube-controllers
    - k8s-app=calico-apiserver
