# code: language=ansible
---
- name: "Disable swap"
  ansible.builtin.command: swapoff -a
  changed_when: true
  when: ansible_facts['swaptotal_mb'] > 0

- name: "Remove swap from fstab"
  ansible.builtin.lineinfile:
    path: '/etc/fstab'
    regexp: '\sswap\s'
    state: 'absent'
