# code: language=ansible
---
- name: "Create kernel modules auto-load config"
  ansible.builtin.template:
    src: "containerd_kernel_modules.j2"
    dest: "{{ k8s_prep_node_kernel_modules_config }}"
  notify: "Restart systemd-modules-load"

- name: "Trigger the handler"
  ansible.builtin.meta: refresh_inventory
