# code: language=ansible
---
- name: "Disable apparmor"
  ansible.builtin.include_tasks: disable_apparmor.yml

- name: "Disable UFW"
  ansible.builtin.include_tasks: disable_ufw.yml

- name: "Install common packages"
  ansible.builtin.include_tasks: install_common_packages.yml
  loop: "{{ k8s_prep_node_common_packages }}"

- name: "Install pip modules"
  ansible.builtin.include_tasks: install_pip_modules.yml
  loop: "{{ k8s_prep_node_pip_modules }}"

- name: "Configure k8s and docker repositories"
  ansible.builtin.include_tasks: configure_repositories.yml
  loop: "{{ k8s_prep_node_repos }}"

- name: "Disable linux swap"
  ansible.builtin.include_tasks: disable_swap.yml

- name: "Install k8s and containerd packages and put them on hold"
  ansible.builtin.include_tasks: install_and_hold_k8s_packages.yml
  loop: "{{ k8s_prep_node_k8s_packages }}"

- name: "Show held packages"
  ansible.builtin.include_tasks: show_held_packages.yml

- name: "Load kernel modules needed by containerd permanently"
  ansible.builtin.include_tasks: kernel_modules_load_permanently.yml

- name: "Configure sysctl parameters needed by containerd"
  ansible.builtin.include_tasks: configure_sysctl_params.yml
  loop: "{{ k8s_prep_node_sysctl_params }}"

- name: "Create containerd and crictl configuration"
  ansible.builtin.include_tasks: create_containerd_and_crictl_config.yml

- name: "Enable autocompletion for kubeadm, kubectl and crictl"
  ansible.builtin.include_tasks: make_autocompletion.yml
