# code: language=ansible
---
galaxy_info:
  author: "Anatoliy Kopylov"
  description: "Fully prepare OS for k8s cluster bootstrap"
  min_ansible_version: "2.14.3"
  license: BSD
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
